[package]
name = "app_bundler"
version = "0.1.0"
authors = ["einzigartigerName <nelson.gillo@gmx.de>"]
edition = "2018"

[dependencies]
rust-embed = "5.6.0"

[workspace]
members = [
    "gui",
    "cli",
]

[profile.release]
lto = "yes"
