[package]
name = "app_bundler"
version = "0.1.0"
authors = ["einzigartigerName <nelson.gillo@gmx.de>"]
edition = "2018"

[dependencies]
rust-embed = "5.6.0"
clap = "2.33.3"

[profile.release]
lto = "yes"
